### ISSUE TITLE
Commander view should merge information from multiple sources.

### ISSUE THREAD

**Issue by ruifung** [corenting/EDCompanion#88]
I.e. Frontier API has ships and basic info, but no progress to next rank.

Inara API has progress to next rank but no ships info.

Perhaps it would be good to query both and merge the info for display.

**Comment by corenting** [comment]
Sorry, just saw the issue :) It was the idea at first, but I didn't have any time to implement it yet :/

**Comment by corenting** [comment]
Sorry for the delay, the feature has been reworked in version 2.15.0 that is currently rolling out to users in the Play Store.
If you want to test it now you can also directly get the APK [here](https://github.com/corenting/EDCompanion/releases/tag/v2.15.0).

You can now enable all services (Inara, EDSM, Frontier) at the same time and the app will pick the most complete source for each information.
